apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::651956763484:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::651956763484:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1F8NNJT9VYLLA
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-10T17:43:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1399"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ce608d89-eda6-4325-b874-85eaee4192ca
