apiVersion: v1
data:
  mapRoles: |
    - groups:
    - system:masters
    rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
    username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::651956763484:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-3H24YN49OX3W
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-02-09T14:58:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1310"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9aa8ab4b-2ba9-4c78-97c3-86a89f6327d2
